# Generated by Django 3.2.7 on 2021-09-18 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
