# Generated by Django 3.2.7 on 2021-09-18 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
